### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by naraujobianchi** [i-like-robots/groundwork-components#3]
Hello,
I'm using the dropdown component for a menu in a project. 
The problem I have is that I need the [data-behaviour=label] to work as a link when it is clicked in a second time and the dropdown is already opened.

Thx,
Nicole =D

**Comment by i-like-robots** [comment]
That's a pretty simple bit of functionality, I'm sure you could do it ;-) You can hack on the dropdown on JSFiddle, http://jsfiddle.net/i_like_robots/bywu9/

**Comment by i-like-robots** [comment]
Did you do any work on this or can I close this issue? I realised too that if the label no longer behaves as a toggle how would a user close it again?
